### PR TITLE
Add SMF 2.1 support to the SMF 2.0 authenticator

### PR DESCRIPTION
**Pull request by webgeek1234**

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Comment by Kissaki** [comment]
@webgeek1234 Was this tested and does this work for you??

The SMF 2.1 check doesn’t make sense to me.

* Rather than a known salt from the database it uses the target hash to compare against. This seems wrong.
* It uses hashpw when it should use checkpw

**Comment by Kissaki** [comment]
@davidebeatrici What was your context for approving this? How deep did you verify? Just a look of unknown code, or knowing or checking methods and how they are used? I presume no test?

**Comment by Kissaki** [comment]
I’m not too familiar with the python landscame. Can you point me to/tell me where/if there is a reference documentation for the hashpw function? I would like to know in what cases the exception is thrown.

**Comment by Kissaki** [comment]
Okay, I guess I will have to test it on an instance to understand it…

**Pull request merged**
